general {
    colors = true
    interval = 1
    output_format = "i3bar"
}

order += "volume master"
order += "disk /"
order += "memory"
order += "tztime local"

volume master {
    format = "%volume"
    format_muted = "muted %volume"
    device = "default"
    mixer = "Master"
    mixer_idx = 0
}

memory {
    format = "%used"
    threshold_degraded = "1G"
    threshold_critical = "200M"
    format_degraded = "MEMORY < %available"
}

tztime local {
    format = "%d-%m-%Y %H:%M:%S"
}
