# Disable all animations
backend = "glx";
glx-no-stencil = true;
glx-no-rebind-pixmap = true;
vsync = true;
shadow = false;
fading = false;
animations = false;

unredir-if-possible = false;

# Reduce blur effects (can impact performance)
blur-background = false;
blur-method = "none";

